# Read the Action.c file generated by Load Runner's scripting of MDS queries.
# export each GetResponse (MDS query) into an .sql file which can be executed
#   directly against HANA via hdbsql with the CALL EXECUTE_MDS procedure

import re 

root='/Users/user_name/Downloads/HANA_Scripts/'
out_n = 0
oout_num = 0
done = False
write = False
GetResponse = False
fullout = ''
fulloutw=''
with open('{}/Action.c'.format(root)) as in_file:
    while not done: #loop over lines in inuput file and write to output file
        try:
            line = next(in_file)
        except StopIteration:
            done = True
            break
        if "lr_start_transaction" in line:
            trx = line.split('"')[1::2][0]
        if "web_custom_request(\"GetResponse_" in line:
            out_n = (re.findall(r'\d+', line))
            out_num = out_n[0].zfill(3)
            GetResponse = True
        if "LAST" in line:
            if GetResponse == True:
                write = False
                GetResponse = False
                fullout+=line
                fulloutw = fullout.replace('\t\t','')\
                                  .replace('\\r','')\
                                  .replace('\\n','\n')\
                                  .replace('\"','')\
                                  .replace('\\','\"')\
                                  .replace(', LAST);','\n\',?);')\
                                  .replace(',LAST);','\n\',?);')
                f = open('{}/GetResponse_{}_{}.sql'.format(root, out_num, trx), 'a')
                f.write(fulloutw)
                f.close()
                fullout=''
                fulloutw=''
        if "Body" in line:
            if GetResponse == True:
                write = True
        if write == True:
            output = line.replace('\n', '')\
                         .replace('Body=','CALL PUBLIC.EXECUTE_MDS (\n\'Analytics\',\'\',\'\',\'\',\'\',\'\n')
            fullout+=output
